### ISSUE TITLE
Isolated Containers

### ISSUE THREAD

**Issue by amcdnl** [pleerock/typedi#1]
Is it possible to not use a global container and use isolated private containers?  So like this:

```
let myContainer = new Container();
myContainer.set(....)
let coffeeMaker = myContainer.get<CoffeeMaker>(CoffeeMaker);
```

most of the other libraries I see do this, like:
- https://github.com/toms-dev/TypeScriptDependencyInjection
- https://github.com/footballradar/jecht

**Comment by PLEEROCK** [comment]
if its possible its a bit tricky, because decorators anyway can register its metadata only in a single global place. To achieve this you must explicitly say in which container you are registering this service, something like this:
`@Service('serviceName', 'mySecondContainer')`

**Comment by amcdnl** [comment]
Ya, I think thats why libraries like IoC libraries like ninject and structuremap in .NET don't have decorators for registry.

**Comment by pleerock** [comment]
closing this issue for now.
