### ISSUE TITLE
Using a Factory to Create Services

### ISSUE THREAD

**Issue by slavafomin** [pleerock/typedi#10]
Hello!

Thank you for this great module!

However, is it possible to instantiate services by calling a factory function instead of the constructor of the specified class?

I know, [you can use](https://github.com/pleerock/typedi/blob/master/sample/sample6-provide/app.ts#L11-L14) `Container.provide()` to add instances directly to the container, but this will force us to instantiate all instances during container initialization stage. The better approach would be to provide a factory function, which will be called by the container when the instance is first requested from it (i.e. lazy instantiation).

Here's the example of the desired code:

```typescript

// The "Bus" class is registered, but not yet instantiated.
// Factory function is specified by the "factory" property.
Container.provide([{
  type: Bus,
  factory: BusFactory.create
}]);

// The "Bus" class is instantiated by calling
// the "BusFactory.create" factory, then instance is returned.
// Without this call, "Bus" will never be instantiated.
const bus = Container.get(Bus);

bus.drive();

// Bus factory is responsible for creating new buses.
class BusFactory {
    // Logger instance should be injected by DI container automatically.
    public static create (Logger: logger) {
        logger.debug('Creating a new Bus');
        return new Bus();
    }
}

class Bus {
    constructor (private Logger: logger) {
        logger.debug('Bus is created');
    }
    drive () {
        this.logger.debug('Bus is moving');
    }
}

```

Also, the factory function itself must be able to rely on values injected by DI container.

Right now, I'm using Angular 2 DI Container in my Node.js application (it supports factory functions), but it's API is somewhat cumbersome and limited. I really like the API of your Container, especially the use of annotations, but lack of the factory functions support is stopping me from migrating.

Also, here's how this implemented in Symfony: [Using a Factory to Create Services](http://symfony.com/doc/current/service_container/factories.html).

Are you planning to add support for factory functions? Or have I somehow missed it? Or could you recommend some workarounds?

Thanks!

**Comment by pleerock** [comment]
fixed in #17 and #18 thanks @slavafomin
