### ISSUE TITLE
Add ability to clear the container

### ISSUE THREAD

**Issue by slavafomin** [pleerock/typedi#12]
As discussed here: https://github.com/pleerock/typedi/pull/11#discussion_r110646471 we need a way to clear the "dirty" container effectively removing all registered services, instances and param handlers. This will allow us to have more isolated unit tests.

**Comment by pleerock** [comment]
`replace` was a bad idea I think. `Container.clear(containerName = "default")` looks better but Im not 100% satisfied with this, however I don't see any other options right now.
