### ISSUE TITLE
Create Factory services

### ISSUE THREAD

**Issue by booradleys** [pleerock/typedi#17]
Hi,
What's the correct way to use factory services.
Usually, (in my Php projects), i'm using a service locator.

Ex: 

public function createService(ServiceLocatorInterface $serviceLocator)
    {
        $config  = $serviceLocator->get('Config');
        $om = $serviceLocator->get('om');
        
        $abonnementMapper = $om->getRepository('Membre\Entity\MembreAbonnement');

        $instance = new AbonnementService();
        $instance->setAbonnementMapper($abonnementMapper);                

        return $instance;
    }

Can you tell me how to do such a thing with TypeDi ?
David

**Comment by pleerock** [comment]
this feature is coming in next release via #11 by @slavafomin

**Comment by booradleys** [comment]
Thank you very much @pleerock .
You're doing a great great job.
I'm using typeorm, typedi and routing-controllers.
Awesome modules !
