### ISSUE TITLE
@Service required?

### ISSUE THREAD

**Issue by amcdnl** [pleerock/typedi#2]
Is `@Service` always required for constructor injection like:

```
@Service() <===== this
class CoffeeMaker {

    private beanFactory: BeanFactory;
    private sugarFactory: SugarFactory;
    private waterFactory: WaterFactory;

    constructor(beanFactory: BeanFactory, sugarFactory: SugarFactory, waterFactory: WaterFactory) {
        this.beanFactory = beanFactory;
        this.sugarFactory = sugarFactory;
        this.waterFactory = waterFactory;
    }
}

let coffeeMaker = Container.get<CoffeeMaker>(CoffeeMaker);
coffeeMaker.make();
```

seems odd, but maybe you need it for something under the hood?

**Comment by PLEEROCK** [comment]
`@Service` decorator collects parameters metadata (constructor parameter types) and later uses it when initializes service to inject proper depend services.
Technically its possible not to use `@Service` decorator if you your class does not have constructor parameters (other service injects). But its better always to use it.

**Comment by amcdnl** [comment]
Gotcha, I think the terminology is a bit wonky for me and throwing me off. 

Not sure what the best way, [jecht](https://github.com/footballradar/jecht) uses keywords like `Inject` on something like above and `Provides` on what you call named services. Just a thought.

**Comment by desmap** [comment]
@pleerock I'm also confused by @Service vs @Inject. @Service also injects [the Container] but should be used when your class has a constructor with params, right?

**Comment by desmap** [comment]
@pleerock, after digging deeper I understood:
1. `@Inject()` injects `Container` into decorated class properties<br>*Hint: InjectIntoProp*
2. `@Service()` injects `Container` into decorated classes<br>*Hint: InjectIntoClassViaConstructorParams*
3. `@Service{'<name>')` injects `Container` into decorated classes and provides that classes via `<name>` via `Container.get('<name>')` <br>*Hint: InjectIntoClassViaConstructorParamsAndProvideAlias*

1 is mandatory for classes without a constructor. 2 is mandatory if a constructor with params injects the dependency.

Right?

**Comment by NoNameProvided** [comment]
I have edited the question and answer. Locking conversation. If you experience any issue please open a new issue.
