### ISSUE TITLE
Move reflection logic from decorators to service layer

### ISSUE THREAD

**Issue by slavafomin** [pleerock/typedi#22]
From: https://github.com/pleerock/routing-controllers/issues/116#issuecomment-296540415

> pleerock: But I think we can resolve this issue and move reflect-metadata read from @Service decorator in some other place in the Container and check if it will work this way.

> slavafomin: Considering moving reflection to the service layer — I think it's the best way to go. We will have centralized place where container is configured and decorators could be very thin, so their functionality could easily be replicated in other "aggregating" decorators of sort. And the DI could be configured without using any decorators at all, which is good for classes coming from third-party libraries where you can't add  decorators.

**Comment by pleerock** [comment]
done in 9d2948c released in `0.5.1`. Can you please check if routing-controllers now work with `@Service` decorator?

**Comment by slavafomin** [comment]
@pleerock Will do, thanks!

**Comment by slavafomin** [comment]
@pleerock It appears to be working great :)

**Comment by pleerock** [comment]
cool, lets close this then
