### ISSUE TITLE
Accessing sources from npm package

### ISSUE THREAD

**Issue by slavafomin** [pleerock/typedi#25]
Hello!

I have a project in which I use `typedi` through `npm`. The npm-package includes source-map files for all `.js` files. However, those source maps reference original files like this: `../../src/Container.ts`, so this path leads outside of `node_modules` directory and points to non-existent source files.

I'm using `source-map-support` module to make stack traces more readable, but the source maps of `typedi` make reported paths weird. It tries to resolve them to files in my project. This complicates debugging.

Actually, I would love those stack traces to be resolved back to original TypeScript files, but sadly the npm-package doesn't contain source files at all. If source files were present it would allow to much easier trace and resolve errors in projects and even to use debugger to dive into internals of `typedi` when used with the real project (this really helps with integration).

So, I think there could be two courses of action:

**1). Add source `.ts` files to the npm-package.**

**2). Remove source maps from npm package because they point to inexistent files.**

Does it makes sense?

Thank you.

**Comment by NoNameProvided** [comment]
Shipping Typescript files instead of plain js files would make this project consumable by Typescript projects only, while now it can be used with plain JS as well.

Also shipping TS files is considered as a bad practice. (I don't know the why. :( )

**Comment by pleerock** [comment]
no, we cant ship ts files with package, it should not be done at all. If source maps point to wrong location then they simply need to be fixed. Try to debug and figure out why paths aren't valid.

**Comment by slavafomin** [comment]
Why don't you want to treat TypeScript files as a first class citizens? We are developing a TypeScript modules are we not? The generated `.js` files should be actually treated like secondary ones and only for the sake of users who don't want to compile them themselves.

> Shipping Typescript files **instead of** plain js files would make this project consumable by Typescript projects only...

I totally agree with you, but I've never proposed to ship them **instead of** `.js`, I'm proposing to ship them as a main code and ship generated `.js` additionally to `.ts` for better compatibility with native (vanilla) JavaScript projects. So the `package = TS [+ JS]`.

It's really nice to have source files inside `node_modules`, because when error happens, or when you debugging things interactively with IDE you can just click on a stack trace and navigate around the call stack. This is invaluable when integrating project with third-party dependencies. And I truly believe that this must be an integral part of great developer experience. For example `reflect-metadata` module contains source files and it makes working with this module very convenient.

It's very helpful to see method or class implementation when you navigate around classes, but instead you have to see blunt typings. So in order to study internals of the `typedi` or `typeorm` I have to open them in a separate window as a separate IDE project and to copy-paste class names or paths to files. This makes no sense at all.

> no, we cant ship ts files with package, it should not be done at all

Could you elaborate on this please? What are the actual drawbacks?

> If source maps point to wrong location then they simply need to be fixed. Try to debug and figure out why paths aren't valid.

How do you propose to fix them? The source maps only contain a reference to the original source file, which allows to resolve the actual place in it. If there is no source files in the package, then there is no sense for keeping the source maps, because it breaks the IDE (source-maps just point nowhere). It would be even better without source maps at all — at least you will be able to see the error in generated `.js` files instead of broken references.

**Comment by pleerock** [comment]
> Could you elaborate on this please? What are the actual drawbacks?

I can't remember at the moment. Last time I did it was few years ago and I faced lot of unresolvable problems. Don't remember what were the problems. Probably this needs research to refresh the memory 

>  The source maps only contain a reference to the original source file, which allows to resolve the actual place in it. 

Im not sure but I think code can be embed into source maps, probably need some research there...

**Comment by slavafomin** [comment]
@pleerock So, your reaction was superstitious. I will strongly suggest to review this matter and I would really love to see these libraries published as TypeScript files. If you want, I can create a sample package in order to test if it works correctly and is not raising any problems. Probably a lot have changed since you've tried this the last time.

@NoNameProvided do you have any thoughts on this?

**Comment by NoNameProvided** [comment]
I am no source-map expert, I only have examples. Both Angular and Ionic team stopped shipping their TS files for various problems. The only one I remember now is having duplicated typings which cause errors with VS Code and other IDEs which are aware of TS.

**Comment by slavafomin** [comment]
I see. However, why do we need typings when source files are available? I always though that typings are for legacy JavaScript code to make it usable with TypeScript. I'm I wrong?

**Comment by NoNameProvided** [comment]
Typings are for TS users, to get the benefits of types even after the project is compiled down to JS.

Anyway I think @pleerock is right about this: 

> Im not sure but I think code can be embed into source maps, probably need some research there...

So instead of not compiling to JS we should research how generate proper map files.

**Comment by pleerock** [comment]
@slavafomin I suggest you to deeply research this question and understand why other libraries do not ship ts files instead of typings. Understand why others not packaging ts sources with package (its not only about angular, ionic). Understand how debugging is done in lets say angular. Btw there is [one article I found](https://medium.com/@mweststrate/how-to-create-strongly-typed-npm-modules-1e1bda23a7f4) that does not recommend to publish ts in packages.

**Comment by 19majkel94** [comment]
`routing-controllers` (at least 0.6.11) has ts source files inside package alongside js and map files. I've never had any issues with importing and duplicated types thanks to correctly set `"main": "index.js", "typings": "index.d.ts"` and debugging show the source file instead of transpiled garbage which is great 😉

**Comment by pleerock** [comment]
no, it does not. It has only js files, source maps and .d.ts files in the package

**Comment by 19majkel94** [comment]
> Btw there is one article I found that does not recommend to publish ts in packages.

It treat about TS 1.6 so it's a bit out of date. My experiments prove that VSCode handle ts source in package very well. There is no compile error or sth, tsc and VSCode treat this *.ts file like it doesn't exist, they doesn't parse it so no error is raised even if I delete a half of the source code 😆 

However ts source file takes precedence over *.d.ts file when "typings" or "types" is not defined in package.json.

**Comment by pleerock** [comment]
I remember when I did it last time I had problems, but it was a few years ago, maybe things changed from those times. For now I don't see a reason why we shall include ts files in the package. If someone disagree we need to discuss it in details and maybe implement in all packages, not just typedi.
