### ISSUE TITLE
need to use require to be able to have services

### ISSUE THREAD

**Issue by digitalkaoz** [pleerock/typedi#28]
hey, another weird issue:

```ts
// services.ts
import {Token, Service, Inject} from 'typedi'

export declare interface IFoo {
  foo(): void
}

const FooImpl = new Token<IFoo>()

@Service(FooImpl)
export class Foo implements IFoo {
  foo (): string {
    return 'foo'
  }
}

@Service('bar')
export class Bar {

  @Inject(FooImpl.name)
  public foo: Foo
}
```

use case 1.

```ts
//main.ts
import 'reflect-metadata'

import {Container} from 'typedi'
console.log(Container.services) //made it public for testing
```

-> nothing inside `services`

use case 2.

```ts
//main.ts
import 'reflect-metadata'

import {Container} from 'typedi'
import {Foo, Bar} from './services'

console.log(Container.services) //made it public for testing
```

-> nothing inside `services`

use case 3.

```ts
//main.ts
import 'reflect-metadata'

import {Container} from 'typedi'
require('./services')

console.log(Container.services) //made it public for testing
```

-> all services from `services.ts` are available in container

personally i would prefer 1. but that seems to be unpossible i think
2. should work, i dunno why, maybe tsc optimizes the unused import away?!
3. is okish, but should be documented i think

**Comment by pleerock** [comment]
1. right its impossible
2. right it strips unused imports
3. this is how javascript works and everybody should know about it. I don't think it should be documented because noone needs to get service without import. When you get service you do `Container.get(SERVICE)` and `SERVICE` is automatically imported.

**Comment by digitalkaoz** [comment]
yeah maybe its my setup...i wrapped your container to do some upfront injections...this container passthru `get<T>(service)` to your container. so the automatic import wont work here...

i have to think over my setup. but anyway thanks for you awesome typescript container :)
