### ISSUE TITLE
Somehow when there are more than ~4 injections there is an error: cannot read property "bind" of undefined

### ISSUE THREAD

**Issue by idchlife** [pleerock/typedi#29]
0|Browser- | TypeError: Cannot read property 'bind' of undefined
    0|Browser- |     at Function.Container.get

Removing dependency removes error.

Using like this:

```
const playerService = Container.get(PlayerService);
```

Does not help. Gives the same error.
Using at runtime gives the same error. (the funny thing, even not calling method directly but just writing Container.get there)

There are no circular dependencies between services.

Full error log:

```
0|Browser- | TypeError: Cannot read property 'bind' of undefined
0|Browser- |     at Function.Container.get (~/node_modules/typedi/Container.js:64:39)
0|Browser- |     at Object.getValue (~/node_modules/typedi/decorators.js:31:70)
0|Browser- |     at ~/node_modules/typedi/Container.js:110:40
0|Browser- |     at Array.forEach (native)
0|Browser- |     at Function.Container.applyPropertyHandlers (~/node_modules/typedi/Container.js:105:14)
0|Browser- |     at Function.Container.get (~/node_modules/typedi/Container.js:66:14)
0|Browser- |     at Object.getValue (~/node_modules/typedi/decorators.js:31:70)
0|Browser- |     at ~/node_modules/typedi/Container.js:110:40
0|Browser- |     at Array.forEach (native)
0|Browser- |     at Function.Container.applyPropertyHandlers (~/node_modules/typedi/Container.js:105:14)
```

**Comment by pleerock** [comment]
no, it should not depend on number of injections. Can you provide a demo repo with problem reproduction so I can take a closer look?

**Comment by idchlife** [comment]
Unfortunately application where I'm using injections is rather large, so it will be problematic to reproduce the problem.

I'll try to debug place mentioned in the error, maybe there something trying to be service and it cannot

Created an issue for reason - maybe you know such case or something. I'll update it soon.

**Comment by idchlife** [comment]
@pleerock what I learned - the error exists when I'm using service inside another service. When I use @Inject() in controllers - everything is ok.

Also I learned that service which causes errors - extending abstract class (which is not service but just class for some services to extend, with basic functionality). There are several other services which extends this abstract class.
I will try to investigate more, but maybe this info will tell you something.

**Comment by pleerock** [comment]
most probably you have circular reference issue. Its not have to be `A <-> B`, it also can be `A <- B <- C <-D <- E <- A`

**Comment by idchlife** [comment]
@pleerock maybe it's that. Maybe this is the issue?

this is service which dies. It uses class IntroLocation (which is not service, because there will be numerous classes like this, also they should be found by name in this my "container".

![image](https://cloud.githubusercontent.com/assets/4563032/26099976/1fac4dde-3a35-11e7-8a4f-a4a249516306.png)

LocationService will register at least ~20 such classes in the future. For getting by name: string, for creating instances etc.


But there is IntroLocation, which has these usages:

![image](https://cloud.githubusercontent.com/assets/4563032/26100035/5496f026-3a35-11e7-92ec-08f9658d6703.png)

And many other classes similar to IntroLocation will have usages of many services.

As you can see I pointed inventoryService. Which uses service which uses LocationService.

I guess that's where it dies. Is there any way I can define type or something in Container.get() ?

**Comment by pleerock** [comment]
why are you using `Container.get` and not regular constructor injection? I need a smallest possible reproduction example, but Im quite sure you have this issue because of circular dependencies.

**Comment by idchlife** [comment]
@pleerock because IntroLocation is class which registered tighly coupled with it's name property in my own container for locations.
When using any kind of injection - since I'm doing new IntroLocation() in my container (not typedi) manually (registering it there) - it would not trigger any kind of injection.

Basically making service out of IntroLocation since it is registered in different place - is not possible.

IntroLocation is not a service. But it should be able to use services.

I will try to create reproduction example when I will use it again and post here.

**Comment by idchlife** [comment]
closing now, don't really have time to provide example.
For those seeking I must say at least one thing: if you have objects that do use entityManager, another services outside "scope of container", where decorator-dependencies are not possible:

use Container.get inside constructor of those objects. Error exists because of getting services in the scope of module, initializing them not at the time of usage, but at the time of importing modules.

not right:

    const service = Container.get(Service);

    export class A {
      // Using somewhere service
    }

right:

    export class A {
      private service: Service = Container.get(Service);
    }
