### ISSUE TITLE
How to inject Request/Session object into service classes ?

### ISSUE THREAD

**Issue by booradleys** [pleerock/typedi#36]
Hi there,
I don't know how to inject Request/Session object into service classes.
Here is what i do and does not work :

LocalisationFactory.ts:
````
import {Inject,Service} from "typedi";
import {Request} from "express";
import { Localisation } from "./Localisation";

@Service()
export class LocalisationFactory
{
    @Inject()
    request: Request;
    
    create()
    {
        let instance = new Localisation();
        instance.setRequest(this.request);               
        return instance;
    }
}
````

**Comment by stackia** [comment]
Same question here.
How to inject koa ctx object into service classes?

**Comment by pleerock** [comment]
you can't do that. You can only inject services and services are global. Request/response objects are not global and they are simple per-request variables passing to your controller/request callback function.

**Comment by booradleys** [comment]
Thank you @pleerock

**Comment by pleerock** [comment]
But in #24 there is a proposal which may resolve this issue once its implemented
