### ISSUE TITLE
Support @PostConstruct

### ISSUE THREAD

**Issue by Diluka** [pleerock/typedi#6]
Like Spring `@PostConstruct`, define a method which invoked after the object has been created and injected. So, we can do some init like a constructor.

**Comment by pleerock** [comment]
If you want to do "some init" why not to use constructor. 

> method which invoked after the object has been created and injected.

object created once but can be injected multiple times.

Im not sure of value of this feature.

**Comment by Diluka** [comment]
Sorry I mean only created

**Comment by pleerock** [comment]
anyway I dont see value in the feature. You can do what ever you want in a constructor if you want to do something on object construction.

**Comment by Diluka** [comment]
how about call this instance method in constructor

**Comment by pleerock** [comment]
what do you mean?

**Comment by Diluka** [comment]
Sometimes, when we initialize an instance, we use content from the injection. And these injected content belongs to the instance of the member, can not be called in the constructor.

**Comment by Diluka** [comment]
I tried it, in JS, you can actually call the member function in the constructor. I may be wrong.

**Comment by Diluka** [comment]
Now, I finally got the purpose of this feature.

This is happened when I use `TypeORM`.

This is a custom `Repository`
```ts
@Service()
@EntityRepository(Entity)
export class CustomRepository extends Repository<Entity>{
}
```

And I am trying to have a property of entity columns with initial value
```ts
@Service()
@EntityRepository(Entity)
export class CustomRepository extends Repository<Entity>{
    columns:string[] = this.metadata.columns.map(o => o.propertyName);
}
```

But crashed. Because initial value will be compiled into `constructor` and it will not call the `super`.

Then I try
```ts
@Service()
@EntityRepository(Entity)
export class CustomRepository extends Repository<Entity>{
    columns:string[] = this.metadata.columns.map(o => o.propertyName);

    constructor(){ super() }
}
```

Still crashed. Because I don't know how to create a `Repository` . And of course I should not to know how to create it. It is factory's work.


So if we had this feature, this will be like
```ts
@Service()
@EntityRepository(Entity)
export class CustomRepository extends Repository<Entity>{
    columns:string[];

    @PostConstruct()
    init(){
        this.columns = this.metadata.columns.map(o => o.propertyName);
    }
}
```


So, what do you think? Should this issue be reopened? @pleerock

**Comment by pleerock** [comment]
you shall be able to do:

```ts
@Service()
@EntityRepository(Entity)
export class CustomRepository extends Repository<Entity>{
    columns:string[];

    constructor(){ 
          super(...arguments);
          this.columns = this.metadata.columns.map(o => o.propertyName);
 }
}
```

Its not different then what you wanted to achieve with ` @PostConstruct()`

**Comment by jasperblues** [comment]
`@PostConstruct` is for using with property injection.

**Comment by jasperblues** [comment]
Another possibility for `@PostConstruct` (in javascript) is that it the post construct method could be `async`, although this would break `Container.get` - a new async version would be required.

**Comment by Diluka** [comment]
`typedi` is a simple IoC container. @jasperblues Maybe you need more complex life cycle control. See [nestjs](https://docs.nestjs.com/faq/lifecycle-events) which is an IoC web framework inspired by `angular`.

**Comment by jasperblues** [comment]
@Diluka The way that NestJS does it (implementing an interface) is good, however it is also nice to support decorators for this purpose. 

Rationale: If you're putting some external library into the DI container, to be consumed by other services, you might not be able to control what is the required post-init method. 

(Also you might not be able to use constructor injection, which is the rationale for a PostConstruct feature).
