### ISSUE TITLE
Не получается использовать

### ISSUE THREAD

**Issue by korolariya** [pleerock/typedi#7]
пишу так 
````
///<reference path="Render.ts" />
import {Container} from "typedi";
class SomeClass {
    someMethod() {
        console.log('test1');
    }
}
````

let someClass = Container.get(SomeClass);
someClass.someMethod();`

Компилирую в phpstorm 
на выходе 

````
var Template;
(function (Template) {
    var Render = (function () {
        function Render() {
        }
        Render.prototype.test = function () {
        };
        return Render;
    }());
    Template.Render = Render;
})(Template || (Template = {}));
//# sourceMappingURL=Main.js.map
````

Получилось что скомпилился только мой файл 
packege.json
` "build-js": "browserify src/Main.js > main.js | browserify node_modules/typedi/index.js > typeid.js",`

Подключал так 

```
 <script type="text/javascript" src="typeid.js"></script>
    <script type="text/javascript" src="main.js"></script>
```

**Comment by idchlife** [comment]
@korolariya not the problem with this lib. Проблема не в библиотеке, тут уж надо смотреть тебе как компилится все с помощью browserify.

Плюс примеры кода абсолютно разрозненные. Что во что? Что откуда.
